package mychat.rest;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import mychat.domain.ChatService;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/chats")
@Tag(name = "Chat", description = "API for managing chats and messages from a chat.")
public class ChatController {
    private final ChatService chatService;

    public ChatController(ChatService chatService) {
        this.chatService = chatService;
    }

    @PostMapping
    @Operation(
        summary = "Create a new chat with an initial message.",
        description = "Creates a new chat and submits the initial message provided in the request body.")
    @ResponseStatus(HttpStatus.CREATED)
    public ChatResponse create(
            @Valid
            @RequestBody
            @Parameter(description = "The request body containing the initial message for the new chat.", required = true)
            ChatRequest createChatRequest) {
        var chat = chatService.createChatWithMessage(createChatRequest.message().text());
        var messages = chatService
            .findMessagesByChatId(chat.id())
            .stream()
            .map(message -> new MessageResponse(message.id(), message.content(), message.receivedAt()))
            .toList();

        return new ChatResponse(chat.id(), messages, chat.createdAt());
    }

    @GetMapping("{id}")
    @Operation(
        summary = "Retrieve a chat by its ID.",
        description = "Retrieves the chat with the specified ID, including all messages associated with that chat.")
    public ChatResponse findById(
        @NotNull
        @PathVariable
        @Parameter(description = "The ID of the chat to retrieve.", required = true)
        Long id) {
        var chat = chatService.findChatById(id);

        var messages = chatService
            .findMessagesByChatId(chat.id())
            .stream()
            .map(message -> new MessageResponse(message.id(), message.content(), message.receivedAt()))
            .toList();

        return new ChatResponse(chat.id(), messages, chat.createdAt());
    }

    @PostMapping("{id}/messages")
    @Operation(
        summary = "Submits a new message to the chat specified by ID",
        description = "Submits a new message to the chat specified by ID and returns the response message generated by the chat service.")
    @ResponseStatus(HttpStatus.CREATED)
    public MessageResponse sendMessage(
            @NotNull
            @PathVariable
            @Parameter(description = "The ID of the chat to which the message is being sent.", required = true)
            Long id,
            @Valid
            @RequestBody
            @Parameter(description = "The request body containing the message to be sent.", required = true)
            MessageRequest messageRequest) {
        var message = chatService.sendMessageAndReceiveResponse(id, messageRequest.text());
        return new MessageResponse(message.id(), message.content(), message.receivedAt());
    }
}
