spring.application.name=mychat
spring.ai.openai.api-key=${OPENAI_API_KEY}

spring.datasource.url=jdbc:postgresql://localhost:5432/mychat
spring.datasource.username=postgres
spring.datasource.password=postgres